#!/bin/bash
# git commit corn#

 set -e

git clone https://github.com/openebs/e2e-infrastructure.git
 
cd e2e-infrastructure

git config --global user.email "atulabhi@gmail.com"
git config --global user.name "atulabhi"

wget https://raw.githubusercontent.com/atulabhi/flux/master/write-commit.yml
ansible-playbook write-commit.yml -e "repo=$CI_PROJECT_NAME" -e "commit=ci"
rm write-commit.yml

git add .

git commit -m "update baseline-image"

git push  https://$user:$pass@github.com/openebs/e2e-infrastructure.git --all

cd ..

chmod u+x e2e-infrastructure

rm -rf e2e-infrastructure 
