kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-forwarder
  namespace: logging
  labels:
    k8s-app: fluentd-forwarder
data:
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
    </system>

  containers.input.conf: |-
    <source>
      @id fluentd-containers.log
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/es-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag raw.kubernetes.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>

    # Detect exceptions in the log output and forward them as one log entry.
    <match raw.kubernetes.**>
      @id raw.kubernetes
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
    </match>

  output.conf: |-
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>
    # Neglecting logs of fluentd
    <match kubernetes.var.log.containers.**fluentd**.log>
      @type null
    </match>
    # Neglecting logs of kube-system
    <match kubernetes.var.log.containers.**kube-system**.log>
      @type null
    </match>
    # Adding fields for commit_id and pipeline_id
    <filter kubernetes.**>
      @type record_transformer
      <record>
        commit_id c_id
        pipeline_id p_id
      </record>
    </filter>
    
    <match **>
      @type copy
      deep_copy true
      <store>
        @type stdout
      </store>
      <store>
        @type forward
        require_ack_response true
        ack_response_timeout 30
        recover_wait 10s
        heartbeat_interval 1s
        phi_threshold 16
        send_timeout 10s
        hard_timeout 10s
        expire_dns_cache 15
        heartbeat_type tcp
        buffer_chunk_limit 2M
        buffer_queue_limit 32
        flush_interval 4s
        max_retry_wait 15
        disable_retry_limit
        num_threads 8
        <server>
          name fluentd-aggregator
          host fluentd-aggregator
          port 24224
          weight 60
        </server>
      </store>
    </match>
