apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: wordpress-nfs-ingress
 namespace: wordpress-nfs
 annotations:
  nginx.ingress.kubernetes.io/rewrite-target: /
  kubernetes.io/tls-acme: "true"
  kubernetes.io/ingress.class: "nginx"
spec:
 tls:
 - hosts:
   - wordpressjiva.openebs.ci
   secretName: wordpress-nfs-ingress
 rules:
 - host: wordpressjiva.openebs.ci
   http:
     paths:
     - path: /
       backend:
         serviceName: wordpress
         servicePort: 80