---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cstor-disk
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-disk"
#(Optional) Below 3 lines schedules the target pods deployed on the labeled nodes
      # - name: TargetNodeSelector
      #   value: |-
      #       node: appnode
provisioner: openebs.io/provisioner-iscsi
---
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-disk
spec:
  name: cstor-disk
  type: disk
  maxPools: 3
  poolSpec:
    poolType: striped
  # NOTE - Appropriate disks need to be fetched using `kubectl get disks`
  disks:
    diskList:
       - disk-3326ca3a735ba9cbe5a7753d12d5a55a
       - disk-a7b338b9c34058880c89ef75a7896cd0
       - disk-49e1ca76d1901a01ff6f366b8c53e44a
---