apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cfgmap
  namespace: grafana-cstor  
data:
  grafana.ini: |
    #################################### Server ####################################
    [auth.anonymous]
    # enable anonymous access
    enabled = true

    # specify organization name that should be used for unauthenticated users
    org_name = Main Org.

    # specify role for unauthenticated users
    org_role = Viewer
    [auth.basic]
    enabled = false