{
 "title": "OpenEBS Volume Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "OpenEBS",
    "label": "OpenEBS Volume",
    "query": "label_values(openebs_size_of_volume, openebs_pv)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Elapsed time since Volume was provisioned",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_volume_uptime{job=\"openebs-volumes\", openebs_pv=~\"$OpenEBS\"}/60"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "singlestat",
   "description": "Capacity Used by the Volume",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_size_of_volume{openebs_pv=~\"$OpenEBS\"}"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "format": "decgbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "openebs_actual_used{openebs_pv=~\"$OpenEBS\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "content": "<img src=\"https://raw.githubusercontent.com/openebs/chitrakala/master/OpenEBS%20logo/openebs%20logos-03.png\" alt=\"OpenEBS logo\" style=\"height: 40px;\">\n<span style=\"font-family: 'Open Sans', 'Helvetica Neue', Helvetica; font-size: 25px;vertical-align: text-top;color: #bbbfc2;margin-left: 10px;\">OpenEBS</span>\n\n<p style=\"margin-top: 10px;\">You're monitoring OpenEBS Volumes using Prometheus. For more information, check out the <a href=\"http://openebs.io/\">OpenEBS</a> and <a href=\"http://prometheus.io/\">Prometheus</a> projects. If you would like to retain this volume monitoring data and much more, sign-up for <a href=\"http://mayaonline.io/\">MayaOnline</a> </p>"
  },
  {
   "title": "IOPS",
   "type": "graph",
   "description": "IOPS",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(openebs_reads{job=\"openebs-volumes\", openebs_pv=~\"$OpenEBS\"}[1m])/60",
     "legendFormat": "{{Reads}}"
    },
    {
     "expr": "increase(openebs_writes{job=\"openebs-volumes\", openebs_pv=~\"$OpenEBS\"}[1m])/60",
     "legendFormat": "{{Writes}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "description": "Throughput",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "increase(openebs_read_block_count{job=\"openebs-volumes\", openebs_pv=~\"$OpenEBS\"}[1m])/(1024*1024*60)",
     "legendFormat": "{{Read Throughput}}"
    },
    {
     "expr": "increase(openebs_write_block_count{job=\"openebs-volumes\", openebs_pv=~\"$OpenEBS\"}[1m])/(1024*1024*60)",
     "legendFormat": "{{Write Throughput}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Latency",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "((increase(openebs_read_time{job=\"openebs-volumes\", openebs_pv=~\"$OpenEBS\"}[1m]))/(increase(openebs_reads{job=\"openebs-volumes\", openebs_pv=~\"$OpenEBS\"}[1m])))/1000000",
     "legendFormat": "{{Read Latency}}"
    },
    {
     "expr": "((increase(openebs_write_time{job=\"openebs-volumes\", openebs_pv=~\"$OpenEBS\"}[1m]))/(increase(openebs_writes{job=\"openebs-volumes\", openebs_pv=~\"$OpenEBS\"}[1m])))/1000000",
     "legendFormat": "{{Write Latency}}"
    }
   ]
  }
 ]
}