apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-aggregator
  namespace: logging
  labels:
    k8s-app: fluentd-aggregator

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-aggregator
  labels:
    k8s-app: fluentd-aggregator
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  - "pods/log"
  - "nodes/proxy"
  verbs:
  - "get"
  - "watch"
  - "list"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-aggregator
  labels:
    k8s-app: fluentd-aggregator
subjects:
- kind: ServiceAccount
  name: fluentd-aggregator
  namespace: logging
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluentd-aggregator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: fluentd-aggregator
  namespace: logging
  labels:
    k8s-app: fluentd-aggregator
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-aggregator
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: fluentd-aggregator
    spec:
      containers:
      - name: fluentd-aggregator
        image: k8s.gcr.io/fluentd-elasticsearch:v2.2.0
        imagePullPolicy: IfNotPresent
        env:
        - name:  FLUENT_ELASTICSEARCH_HOST
          value: "elasticsearch-logging"
        - name:  FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENT_ELASTICSEARCH_SCHEME
          value: "http"
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 250Mi
        ports:
        - name: fwd-input
          containerPort: 24224
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/fluent/config.d
      volumes:
      - name: config-volume
        configMap:
          name: "fluentd-aggregator"
      # Give the aggregator ample time to flush it's logs
      terminationGracePeriodSeconds: 20
      serviceAccountName: fluentd-aggregator
