apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-forwarder
  namespace: logging
  labels:
    k8s-app: fluentd-forwarder

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-forwarder
  labels:
    k8s-app: fluentd-forwarder
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  - "pods/log"
  - "nodes/proxy"
  verbs:
  - "get"
  - "watch"
  - "list"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-forwarder
  labels:
    k8s-app: fluentd-forwarder
subjects:
- kind: ServiceAccount
  name: fluentd-forwarder
  namespace: logging
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: fluentd-forwarder
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-forwarder
  namespace: logging
  labels:
    k8s-app: fluentd-forwarder
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-forwarder
  template:
    metadata:
      labels:
        k8s-app: fluentd-forwarder
        kubernetes.io/cluster-service: "true"
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: fluentd-forwarder
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd-forwarder
        image: k8s.gcr.io/fluentd-elasticsearch:v2.2.0
        env:
        - name: FLUENTD_CONFIG
          value: fluentd-forwarder.conf
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /etc/fluent/config.d
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config-volume
        configMap:
          name: fluentd-forwarder
