apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgresql-sc
  annotations:
    cas.openebs.io/config: |
      - name: ReplicaCount
        value: "3"
provisioner: openebs.io/provisioner-iscsi
